runtime: nodejs20

# Note: First deployment must be to 'default' service
# After initial deployment, you can uncomment the line below to create a separate service
# service: car-database-api

env_variables:
  PORT: 8080
  NODE_ENV: production

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto
  secure: always

